"""
Free, offline reference data used by the intelligence layer.

Nothing in this module costs money or requires an API key.  The domain catalog
is a curated subset of publicly documented service domains; it is deliberately
compact (a few hundred entries) so it can live in git, and it can be extended at
runtime by:

* the existing ``config/app_domains.json`` file,
* the user's own ``hn_rules`` rows from the Rules tab,
* optional community feed lists imported by ``src.intel.extdata``.

Format: ``(domain, app, category, owner)``.  Matching walks the domain suffixes,
so ``r4---sn-abc.googlevideo.com`` resolves via ``googlevideo.com``.
"""

from __future__ import annotations

CATEGORIES = [
    'Social', 'Video', 'Music', 'Gaming', 'Messaging', 'Communication',
    'Shopping', 'News', 'Education', 'Work', 'Cloud', 'Development', 'Search',
    'AI', 'Adult', 'Gambling', 'Dating', 'Ads & Tracking', 'VPN & Proxy',
    'DNS', 'Files', 'IoT', 'Finance', 'Health', 'Travel', 'Food', 'Sports',
    'Forums', 'Email', 'Security', 'Streaming', 'Unknown',
]

# ---------------------------------------------------------------------------
# Domain catalog
# ---------------------------------------------------------------------------

DOMAIN_CATALOG = [
    # --- Google / YouTube -------------------------------------------------
    ('google.com', 'Google', 'Search', 'Google LLC'),
    ('google.co.uk', 'Google', 'Search', 'Google LLC'),
    ('googleapis.com', 'Google APIs', 'Cloud', 'Google LLC'),
    ('gstatic.com', 'Google Static', 'Cloud', 'Google LLC'),
    ('googleusercontent.com', 'Google User Content', 'Cloud', 'Google LLC'),
    ('googlevideo.com', 'YouTube', 'Video', 'Google LLC'),
    ('ytimg.com', 'YouTube', 'Video', 'Google LLC'),
    ('youtube.com', 'YouTube', 'Video', 'Google LLC'),
    ('youtu.be', 'YouTube', 'Video', 'Google LLC'),
    ('yt3.ggpht.com', 'YouTube', 'Video', 'Google LLC'),
    ('google-analytics.com', 'Google Analytics', 'Ads & Tracking', 'Google LLC'),
    ('googletagmanager.com', 'Google Tag Manager', 'Ads & Tracking', 'Google LLC'),
    ('googlesyndication.com', 'Google Ads', 'Ads & Tracking', 'Google LLC'),
    ('doubleclick.net', 'Google Ads', 'Ads & Tracking', 'Google LLC'),
    ('googleadservices.com', 'Google Ads', 'Ads & Tracking', 'Google LLC'),
    ('gmail.com', 'Gmail', 'Email', 'Google LLC'),
    ('googlemail.com', 'Gmail', 'Email', 'Google LLC'),
    ('docs.google.com', 'Google Docs', 'Work', 'Google LLC'),
    ('drive.google.com', 'Google Drive', 'Files', 'Google LLC'),
    ('photos.google.com', 'Google Photos', 'Files', 'Google LLC'),
    ('meet.google.com', 'Google Meet', 'Communication', 'Google LLC'),
    ('play.google.com', 'Google Play', 'Shopping', 'Google LLC'),
    ('maps.google.com', 'Google Maps', 'Reference', 'Google LLC'),
    ('gemini.google.com', 'Google Gemini', 'AI', 'Google LLC'),
    ('bard.google.com', 'Google Gemini', 'AI', 'Google LLC'),
    ('blogger.com', 'Blogger', 'Forums', 'Google LLC'),
    ('googleclassroom.com', 'Google Classroom', 'Education', 'Google LLC'),
    ('classroom.google.com', 'Google Classroom', 'Education', 'Google LLC'),
    ('android.com', 'Android', 'IoT', 'Google LLC'),
    ('dns.google', 'Google DNS (DoH)', 'DNS', 'Google LLC'),

    # --- Apple ------------------------------------------------------------
    ('apple.com', 'Apple', 'Shopping', 'Apple Inc.'),
    ('icloud.com', 'iCloud', 'Files', 'Apple Inc.'),
    ('icloud-content.com', 'iCloud', 'Files', 'Apple Inc.'),
    ('mzstatic.com', 'Apple Music', 'Music', 'Apple Inc.'),
    ('music.apple.com', 'Apple Music', 'Music', 'Apple Inc.'),
    ('itunes.apple.com', 'Apple Music', 'Music', 'Apple Inc.'),
    ('apps.apple.com', 'App Store', 'Shopping', 'Apple Inc.'),
    ('push.apple.com', 'Apple Push', 'IoT', 'Apple Inc.'),
    ('apple-cloudkit.com', 'iCloud', 'Cloud', 'Apple Inc.'),
    ('apple-dns.net', 'Apple iCloud Private Relay', 'VPN & Proxy', 'Apple Inc.'),
    ('mask.icloud.com', 'Apple iCloud Private Relay', 'VPN & Proxy', 'Apple Inc.'),
    ('apple-relay.cloudflare.com', 'Apple iCloud Private Relay', 'VPN & Proxy', 'Apple Inc.'),

    # --- Meta -------------------------------------------------------------
    ('facebook.com', 'Facebook', 'Social', 'Meta Platforms'),
    ('fb.com', 'Facebook', 'Social', 'Meta Platforms'),
    ('fbcdn.net', 'Facebook', 'Social', 'Meta Platforms'),
    # Reverse-DNS / CDN infrastructure roots.  Without these a PTR name like
    # ``fra16s48-in-f14.1e100.net`` cannot be attributed to anything.
    ('1e100.net', 'Google', 'Search', 'Google'),
    ('googlevideo.com', 'YouTube', 'Video', 'Google'),
    ('ggpht.com', 'Google Photos', 'Storage', 'Google'),
    ('googleusercontent.com', 'Google', 'Cloud', 'Google'),
    ('akamaiedge.net', 'Akamai CDN', 'Cloud', 'Akamai'),
    ('edgekey.net', 'Akamai CDN', 'Cloud', 'Akamai'),
    ('edgesuite.net', 'Akamai CDN', 'Cloud', 'Akamai'),
    ('llnwd.net', 'Limelight CDN', 'Cloud', 'Limelight'),
    ('akadns.net', 'Akamai DNS', 'Cloud', 'Akamai'),
    ('azureedge.net', 'Azure CDN', 'Cloud', 'Microsoft'),
    ('msecnd.net', 'Microsoft CDN', 'Cloud', 'Microsoft'),
    ('fbcdn.net', 'Facebook', 'Social', 'Meta Platforms'),
    ('cdninstagram.com', 'Instagram', 'Social', 'Meta Platforms'),
    ('ttvnw.net', 'Twitch', 'Streaming', 'Amazon'),
    ('aiv-cdn.net', 'Amazon Video', 'Streaming', 'Amazon'),
    ('amazonaws.com', 'AWS', 'Cloud', 'Amazon'),
    ('rsc.cdn77.org', 'CDN77', 'Cloud', 'CDN77'),
    ('cdn77.org', 'CDN77', 'Cloud', 'CDN77'),
    ('jsdelivr.net', 'jsDelivr CDN', 'Cloud', 'jsDelivr'),
    ('unpkg.com', 'unpkg CDN', 'Cloud', 'Cloudflare'),
    ('bamgrid.com', 'Disney+', 'Streaming', 'Disney'),
    ('dssott.com', 'Disney+', 'Streaming', 'Disney'),
    ('hbomaxcdn.com', 'HBO Max', 'Streaming', 'Warner Bros. Discovery'),
    ('spotifycdn.com', 'Spotify', 'Music', 'Spotify'),
    ('scdn.co', 'Spotify', 'Music', 'Spotify'),
    ('licdn.com', 'LinkedIn', 'Social', 'Microsoft'),
    ('twimg.com', 'X (Twitter)', 'Social', 'X Corp.'),
    ('tiktokcdn.com', 'TikTok', 'Social', 'ByteDance'),
    ('tiktokv.com', 'TikTok', 'Social', 'ByteDance'),
    ('muscdn.com', 'TikTok', 'Social', 'ByteDance'),
    ('byteoversea.com', 'TikTok', 'Social', 'ByteDance'),
    ('snapchat.com', 'Snapchat', 'Social', 'Snap Inc.'),
    ('whatsapp.net', 'WhatsApp', 'Messaging', 'Meta Platforms'),
    ('telegram.org', 'Telegram', 'Messaging', 'Telegram'),
    ('fbsbx.com', 'Facebook', 'Social', 'Meta Platforms'),
    ('messenger.com', 'Messenger', 'Messaging', 'Meta Platforms'),
    ('instagram.com', 'Instagram', 'Social', 'Meta Platforms'),
    ('cdninstagram.com', 'Instagram', 'Social', 'Meta Platforms'),
    ('threads.net', 'Threads', 'Social', 'Meta Platforms'),
    ('whatsapp.com', 'WhatsApp', 'Messaging', 'Meta Platforms'),
    ('whatsapp.net', 'WhatsApp', 'Messaging', 'Meta Platforms'),
    ('wa.me', 'WhatsApp', 'Messaging', 'Meta Platforms'),
    ('meta.com', 'Meta', 'Social', 'Meta Platforms'),

    # --- ByteDance / short video -----------------------------------------
    ('tiktok.com', 'TikTok', 'Social', 'ByteDance'),
    ('tiktokcdn.com', 'TikTok', 'Social', 'ByteDance'),
    ('tiktokv.com', 'TikTok', 'Social', 'ByteDance'),
    ('musical.ly', 'TikTok', 'Social', 'ByteDance'),
    ('byteoversea.com', 'TikTok', 'Social', 'ByteDance'),
    ('ibytedtos.com', 'TikTok', 'Social', 'ByteDance'),
    ('capcut.com', 'CapCut', 'Video', 'ByteDance'),
    ('douyin.com', 'Douyin', 'Social', 'ByteDance'),

    # --- Other social -----------------------------------------------------
    ('twitter.com', 'X (Twitter)', 'Social', 'X Corp'),
    ('x.com', 'X (Twitter)', 'Social', 'X Corp'),
    ('twimg.com', 'X (Twitter)', 'Social', 'X Corp'),
    ('t.co', 'X (Twitter)', 'Social', 'X Corp'),
    ('snapchat.com', 'Snapchat', 'Social', 'Snap Inc.'),
    ('sc-cdn.net', 'Snapchat', 'Social', 'Snap Inc.'),
    ('snap.com', 'Snapchat', 'Social', 'Snap Inc.'),
    ('reddit.com', 'Reddit', 'Forums', 'Reddit Inc.'),
    ('redd.it', 'Reddit', 'Forums', 'Reddit Inc.'),
    ('redditmedia.com', 'Reddit', 'Forums', 'Reddit Inc.'),
    ('redditstatic.com', 'Reddit', 'Forums', 'Reddit Inc.'),
    ('pinterest.com', 'Pinterest', 'Social', 'Pinterest Inc.'),
    ('pinimg.com', 'Pinterest', 'Social', 'Pinterest Inc.'),
    ('linkedin.com', 'LinkedIn', 'Work', 'Microsoft'),
    ('licdn.com', 'LinkedIn', 'Work', 'Microsoft'),
    ('tumblr.com', 'Tumblr', 'Social', 'Automattic'),
    ('discord.com', 'Discord', 'Messaging', 'Discord Inc.'),
    ('discord.gg', 'Discord', 'Messaging', 'Discord Inc.'),
    ('discordapp.com', 'Discord', 'Messaging', 'Discord Inc.'),
    ('discordapp.net', 'Discord', 'Messaging', 'Discord Inc.'),
    ('discord.media', 'Discord', 'Messaging', 'Discord Inc.'),
    ('telegram.org', 'Telegram', 'Messaging', 'Telegram FZ-LLC'),
    ('t.me', 'Telegram', 'Messaging', 'Telegram FZ-LLC'),
    ('telegram.me', 'Telegram', 'Messaging', 'Telegram FZ-LLC'),
    ('telegra.ph', 'Telegram', 'Messaging', 'Telegram FZ-LLC'),
    ('signal.org', 'Signal', 'Messaging', 'Signal Foundation'),
    ('viber.com', 'Viber', 'Messaging', 'Rakuten'),
    ('wechat.com', 'WeChat', 'Messaging', 'Tencent'),
    ('qq.com', 'QQ', 'Messaging', 'Tencent'),
    ('imessage.apple.com', 'iMessage', 'Messaging', 'Apple Inc.'),
    ('bereal.team', 'BeReal', 'Social', 'BeReal'),
    ('bsky.app', 'Bluesky', 'Social', 'Bluesky'),
    ('mastodon.social', 'Mastodon', 'Social', 'Mastodon gGmbH'),

    # --- Streaming video --------------------------------------------------
    ('netflix.com', 'Netflix', 'Streaming', 'Netflix Inc.'),
    ('nflximg.net', 'Netflix', 'Streaming', 'Netflix Inc.'),
    ('nflxvideo.net', 'Netflix', 'Streaming', 'Netflix Inc.'),
    ('nflxso.net', 'Netflix', 'Streaming', 'Netflix Inc.'),
    ('disneyplus.com', 'Disney+', 'Streaming', 'Disney'),
    ('dssott.com', 'Disney+', 'Streaming', 'Disney'),
    ('disney.com', 'Disney', 'Streaming', 'Disney'),
    ('hulu.com', 'Hulu', 'Streaming', 'Disney'),
    ('hulustream.com', 'Hulu', 'Streaming', 'Disney'),
    ('espn.com', 'ESPN', 'Sports', 'Disney'),
    ('hbomax.com', 'Max', 'Streaming', 'Warner Bros. Discovery'),
    ('max.com', 'Max', 'Streaming', 'Warner Bros. Discovery'),
    ('hbo.com', 'HBO', 'Streaming', 'Warner Bros. Discovery'),
    ('primevideo.com', 'Prime Video', 'Streaming', 'Amazon'),
    ('amazonvideo.com', 'Prime Video', 'Streaming', 'Amazon'),
    ('twitch.tv', 'Twitch', 'Streaming', 'Amazon'),
    ('ttvnw.net', 'Twitch', 'Streaming', 'Amazon'),
    ('jtvnw.net', 'Twitch', 'Streaming', 'Amazon'),
    ('plex.tv', 'Plex', 'Streaming', 'Plex Inc.'),
    ('plex.direct', 'Plex', 'Streaming', 'Plex Inc.'),
    ('crunchyroll.com', 'Crunchyroll', 'Streaming', 'Sony'),
    ('paramountplus.com', 'Paramount+', 'Streaming', 'Paramount'),
    ('peacocktv.com', 'Peacock', 'Streaming', 'Comcast'),
    ('britbox.com', 'BritBox', 'Streaming', 'BBC/ITV'),
    ('iplayer.bbc.co.uk', 'BBC iPlayer', 'Streaming', 'BBC'),
    ('bbc.co.uk', 'BBC', 'News', 'BBC'),
    ('itv.com', 'ITVX', 'Streaming', 'ITV'),
    ('dailymotion.com', 'Dailymotion', 'Video', 'Vivendi'),
    ('vimeo.com', 'Vimeo', 'Video', 'Vimeo Inc.'),
    ('rumble.com', 'Rumble', 'Video', 'Rumble Inc.'),
    ('kick.com', 'Kick', 'Streaming', 'Kick'),
    ('roku.com', 'Roku', 'IoT', 'Roku Inc.'),

    # --- Music ------------------------------------------------------------
    ('spotify.com', 'Spotify', 'Music', 'Spotify AB'),
    ('scdn.co', 'Spotify', 'Music', 'Spotify AB'),
    ('spotifycdn.com', 'Spotify', 'Music', 'Spotify AB'),
    ('soundcloud.com', 'SoundCloud', 'Music', 'SoundCloud'),
    ('sndcdn.com', 'SoundCloud', 'Music', 'SoundCloud'),
    ('deezer.com', 'Deezer', 'Music', 'Deezer'),
    ('dzcdn.net', 'Deezer', 'Music', 'Deezer'),
    ('tidal.com', 'TIDAL', 'Music', 'Block Inc.'),
    ('pandora.com', 'Pandora', 'Music', 'SiriusXM'),
    ('last.fm', 'Last.fm', 'Music', 'Paramount'),
    ('shazam.com', 'Shazam', 'Music', 'Apple Inc.'),

    # --- Gaming -----------------------------------------------------------
    ('steampowered.com', 'Steam', 'Gaming', 'Valve'),
    ('steamcommunity.com', 'Steam', 'Gaming', 'Valve'),
    ('steamstatic.com', 'Steam', 'Gaming', 'Valve'),
    ('steamcontent.com', 'Steam', 'Gaming', 'Valve'),
    ('epicgames.com', 'Epic Games', 'Gaming', 'Epic Games'),
    ('unrealengine.com', 'Unreal Engine', 'Gaming', 'Epic Games'),
    ('easyanticheat.net', 'Easy Anti-Cheat', 'Gaming', 'Epic Games'),
    ('riotgames.com', 'Riot Games', 'Gaming', 'Tencent'),
    ('leagueoflegends.com', 'League of Legends', 'Gaming', 'Riot Games'),
    ('valorant.com', 'Valorant', 'Gaming', 'Riot Games'),
    ('blizzard.com', 'Blizzard', 'Gaming', 'Microsoft'),
    ('battle.net', 'Battle.net', 'Gaming', 'Blizzard'),
    ('activision.com', 'Call of Duty', 'Gaming', 'Microsoft'),
    ('callofduty.com', 'Call of Duty', 'Gaming', 'Activision'),
    ('minecraft.net', 'Minecraft', 'Gaming', 'Microsoft'),
    ('mojang.com', 'Minecraft', 'Gaming', 'Microsoft'),
    ('roblox.com', 'Roblox', 'Gaming', 'Roblox Corp.'),
    ('rbxcdn.com', 'Roblox', 'Gaming', 'Roblox Corp.'),
    ('fortnite.com', 'Fortnite', 'Gaming', 'Epic Games'),
    ('ea.com', 'EA', 'Gaming', 'Electronic Arts'),
    ('origin.com', 'EA App', 'Gaming', 'Electronic Arts'),
    ('ubisoft.com', 'Ubisoft', 'Gaming', 'Ubisoft'),
    ('ubi.com', 'Ubisoft Connect', 'Gaming', 'Ubisoft'),
    ('playstation.com', 'PlayStation Network', 'Gaming', 'Sony'),
    ('playstation.net', 'PlayStation Network', 'Gaming', 'Sony'),
    ('sonyentertainmentnetwork.com', 'PlayStation Network', 'Gaming', 'Sony'),
    ('xbox.com', 'Xbox Live', 'Gaming', 'Microsoft'),
    ('xboxlive.com', 'Xbox Live', 'Gaming', 'Microsoft'),
    ('nintendo.com', 'Nintendo', 'Gaming', 'Nintendo'),
    ('nintendo.net', 'Nintendo Switch Online', 'Gaming', 'Nintendo'),
    ('garena.com', 'Garena', 'Gaming', 'Sea Ltd'),
    ('supercell.com', 'Supercell', 'Gaming', 'Supercell'),
    ('clashofclans.com', 'Clash of Clans', 'Gaming', 'Supercell'),
    ('hoyoverse.com', 'HoYoverse', 'Gaming', 'miHoYo'),
    ('mihoyo.com', 'Genshin Impact', 'Gaming', 'miHoYo'),
    ('rockstargames.com', 'Rockstar Games', 'Gaming', 'Take-Two'),
    ('twitch.tv', 'Twitch', 'Streaming', 'Amazon'),
    ('discord.gg', 'Discord', 'Messaging', 'Discord Inc.'),
    ('itch.io', 'itch.io', 'Gaming', 'itch Corp.'),
    ('gog.com', 'GOG', 'Gaming', 'CD Projekt'),
    ('faceit.com', 'FACEIT', 'Gaming', 'FACEIT'),
    ('esports.com', 'Esports', 'Gaming', 'Esports'),
    ('chess.com', 'Chess.com', 'Gaming', 'Chess.com'),
    ('lichess.org', 'Lichess', 'Gaming', 'Lichess'),
    ('poki.com', 'Poki', 'Gaming', 'Poki'),
    ('crazygames.com', 'CrazyGames', 'Gaming', 'CrazyGames'),
    ('miniclip.com', 'Miniclip', 'Gaming', 'Miniclip'),
    ('newgrounds.com', 'Newgrounds', 'Gaming', 'Newgrounds'),
    ('coolmathgames.com', 'Coolmath Games', 'Gaming', 'Coolmath'),

    # --- Microsoft / work -------------------------------------------------
    ('microsoft.com', 'Microsoft', 'Work', 'Microsoft'),
    ('windows.com', 'Windows Update', 'Work', 'Microsoft'),
    ('windowsupdate.com', 'Windows Update', 'Work', 'Microsoft'),
    ('live.com', 'Microsoft Account', 'Work', 'Microsoft'),
    ('outlook.com', 'Outlook', 'Email', 'Microsoft'),
    ('office.com', 'Microsoft 365', 'Work', 'Microsoft'),
    ('office365.com', 'Microsoft 365', 'Work', 'Microsoft'),
    ('office.net', 'Microsoft 365', 'Work', 'Microsoft'),
    ('sharepoint.com', 'SharePoint', 'Work', 'Microsoft'),
    ('onedrive.com', 'OneDrive', 'Files', 'Microsoft'),
    ('onedrive.live.com', 'OneDrive', 'Files', 'Microsoft'),
    ('teams.microsoft.com', 'Microsoft Teams', 'Communication', 'Microsoft'),
    ('teams.cdn.office.net', 'Microsoft Teams', 'Communication', 'Microsoft'),
    ('azure.com', 'Azure', 'Cloud', 'Microsoft'),
    ('azurewebsites.net', 'Azure', 'Cloud', 'Microsoft'),
    ('blob.core.windows.net', 'Azure Blob', 'Cloud', 'Microsoft'),
    ('cloud.microsoft', 'Microsoft Cloud', 'Cloud', 'Microsoft'),
    ('msn.com', 'MSN', 'News', 'Microsoft'),
    ('bing.com', 'Bing', 'Search', 'Microsoft'),
    ('skype.com', 'Skype', 'Communication', 'Microsoft'),
    ('xboxservices.com', 'Xbox Live', 'Gaming', 'Microsoft'),
    ('visualstudio.com', 'Visual Studio', 'Development', 'Microsoft'),
    ('github.com', 'GitHub', 'Development', 'Microsoft'),
    ('githubusercontent.com', 'GitHub', 'Development', 'Microsoft'),
    ('githubassets.com', 'GitHub', 'Development', 'Microsoft'),
    ('ghcr.io', 'GitHub Container Registry', 'Development', 'Microsoft'),
    ('copilot.microsoft.com', 'Microsoft Copilot', 'AI', 'Microsoft'),

    # --- Amazon / shopping ------------------------------------------------
    ('amazon.com', 'Amazon', 'Shopping', 'Amazon'),
    ('amazon.co.uk', 'Amazon', 'Shopping', 'Amazon'),
    ('amazon.de', 'Amazon', 'Shopping', 'Amazon'),
    ('amazonaws.com', 'AWS', 'Cloud', 'Amazon'),
    ('aws.amazon.com', 'AWS', 'Cloud', 'Amazon'),
    ('cloudfront.net', 'AWS CloudFront', 'Cloud', 'Amazon'),
    ('amazon-adsystem.com', 'Amazon Ads', 'Ads & Tracking', 'Amazon'),
    ('audible.com', 'Audible', 'Music', 'Amazon'),
    ('twitch.tv', 'Twitch', 'Streaming', 'Amazon'),
    ('zappos.com', 'Zappos', 'Shopping', 'Amazon'),
    ('ebay.com', 'eBay', 'Shopping', 'eBay Inc.'),
    ('ebayimg.com', 'eBay', 'Shopping', 'eBay Inc.'),
    ('aliexpress.com', 'AliExpress', 'Shopping', 'Alibaba'),
    ('alibaba.com', 'Alibaba', 'Shopping', 'Alibaba'),
    ('alipay.com', 'Alipay', 'Finance', 'Ant Group'),
    ('taobao.com', 'Taobao', 'Shopping', 'Alibaba'),
    ('temu.com', 'Temu', 'Shopping', 'PDD Holdings'),
    ('shein.com', 'Shein', 'Shopping', 'Shein'),
    ('wish.com', 'Wish', 'Shopping', 'Wish'),
    ('etsy.com', 'Etsy', 'Shopping', 'Etsy Inc.'),
    ('shopify.com', 'Shopify', 'Shopping', 'Shopify'),
    ('myshopify.com', 'Shopify', 'Shopping', 'Shopify'),
    ('walmart.com', 'Walmart', 'Shopping', 'Walmart'),
    ('target.com', 'Target', 'Shopping', 'Target'),
    ('argos.co.uk', 'Argos', 'Shopping', 'Sainsbury\'s'),
    ('asos.com', 'ASOS', 'Shopping', 'ASOS'),
    ('johnlewis.com', 'John Lewis', 'Shopping', 'John Lewis Partnership'),
    ('amazon.co.jp', 'Amazon Japan', 'Shopping', 'Amazon'),

    # --- News / sport / reference ----------------------------------------
    ('cnn.com', 'CNN', 'News', 'Warner Bros. Discovery'),
    ('bbc.com', 'BBC News', 'News', 'BBC'),
    ('nytimes.com', 'New York Times', 'News', 'NYT'),
    ('theguardian.com', 'The Guardian', 'News', 'Guardian Media Group'),
    ('reuters.com', 'Reuters', 'News', 'Thomson Reuters'),
    ('apnews.com', 'AP News', 'News', 'Associated Press'),
    ('foxnews.com', 'Fox News', 'News', 'Fox Corp'),
    ('dailymail.co.uk', 'Daily Mail', 'News', 'DMG Media'),
    ('skynews.com', 'Sky News', 'News', 'Sky'),
    ('news.sky.com', 'Sky News', 'News', 'Sky'),
    ('espn.com', 'ESPN', 'Sports', 'Disney'),
    ('skysports.com', 'Sky Sports', 'Sports', 'Sky'),
    ('bbc.co.uk/sport', 'BBC Sport', 'Sports', 'BBC'),
    ('wikipedia.org', 'Wikipedia', 'Reference', 'Wikimedia'),
    ('wikimedia.org', 'Wikimedia', 'Reference', 'Wikimedia'),
    ('dictionary.com', 'Dictionary.com', 'Reference', 'IXL'),
    ('imdb.com', 'IMDb', 'Reference', 'Amazon'),
    ('quora.com', 'Quora', 'Forums', 'Quora'),
    ('stackoverflow.com', 'Stack Overflow', 'Development', 'Stack Exchange'),
    ('stackexchange.com', 'Stack Exchange', 'Development', 'Stack Exchange'),
    ('medium.com', 'Medium', 'Forums', 'Medium'),
    ('substack.com', 'Substack', 'News', 'Substack'),
    ('weather.com', 'The Weather Channel', 'News', 'IBM'),
    ('metoffice.gov.uk', 'Met Office', 'News', 'UK Government'),

    # --- Education --------------------------------------------------------
    ('khanacademy.org', 'Khan Academy', 'Education', 'Khan Academy'),
    ('duolingo.com', 'Duolingo', 'Education', 'Duolingo'),
    ('coursera.org', 'Coursera', 'Education', 'Coursera'),
    ('udemy.com', 'Udemy', 'Education', 'Udemy'),
    ('udacity.com', 'Udacity', 'Education', 'Udacity'),
    ('edx.org', 'edX', 'Education', 'edX'),
    ('moodle.org', 'Moodle', 'Education', 'Moodle'),
    ('classroom.google.com', 'Google Classroom', 'Education', 'Google LLC'),
    ('teams.microsoft.com', 'Microsoft Teams', 'Communication', 'Microsoft'),
    ('schoology.com', 'Schoology', 'Education', 'PowerSchool'),
    ('seesaw.me', 'Seesaw', 'Education', 'Seesaw'),
    ('sparxmaths.com', 'Sparx Maths', 'Education', 'Sparx'),
    ('hegartyMaths.com', 'Hegarty Maths', 'Education', 'Hegarty'),
    ('bitesize.bbc.co.uk', 'BBC Bitesize', 'Education', 'BBC'),
    ('quizlet.com', 'Quizlet', 'Education', 'Quizlet'),
    ('scratch.mit.edu', 'Scratch', 'Education', 'MIT'),
    ('brilliant.org', 'Brilliant', 'Education', 'Brilliant'),
    ('mathletics.com', 'Mathletics', 'Education', '3P Learning'),
    ('papers.xtremepapers.com', 'Past Papers', 'Education', 'XTremePapers'),

    # --- AI ---------------------------------------------------------------
    ('openai.com', 'ChatGPT', 'AI', 'OpenAI'),
    ('chatgpt.com', 'ChatGPT', 'AI', 'OpenAI'),
    ('oaistatic.com', 'ChatGPT', 'AI', 'OpenAI'),
    ('oaiusercontent.com', 'ChatGPT', 'AI', 'OpenAI'),
    ('anthropic.com', 'Claude', 'AI', 'Anthropic'),
    ('claude.ai', 'Claude', 'AI', 'Anthropic'),
    ('perplexity.ai', 'Perplexity', 'AI', 'Perplexity'),
    ('character.ai', 'Character.AI', 'AI', 'Character.AI'),
    ('poe.com', 'Poe', 'AI', 'Quora'),
    ('midjourney.com', 'Midjourney', 'AI', 'Midjourney'),
    ('huggingface.co', 'Hugging Face', 'AI', 'Hugging Face'),
    ('elevenlabs.io', 'ElevenLabs', 'AI', 'ElevenLabs'),
    ('deepseek.com', 'DeepSeek', 'AI', 'DeepSeek'),
    ('grok.com', 'Grok', 'AI', 'X Corp'),
    ('copilot.microsoft.com', 'Copilot', 'AI', 'Microsoft'),

    # --- Files / cloud / dev ---------------------------------------------
    ('dropbox.com', 'Dropbox', 'Files', 'Dropbox'),
    ('dropboxstatic.com', 'Dropbox', 'Files', 'Dropbox'),
    ('box.com', 'Box', 'Files', 'Box'),
    ('boxcdn.net', 'Box', 'Files', 'Box'),
    ('mega.nz', 'MEGA', 'Files', 'Mega Ltd'),
    ('wetransfer.com', 'WeTransfer', 'Files', 'WeTransfer'),
    ('pcloud.com', 'pCloud', 'Files', 'pCloud'),
    ('mediafire.com', 'MediaFire', 'Files', 'MediaFire'),
    ('cloudflare.com', 'Cloudflare', 'Cloud', 'Cloudflare'),
    ('cloudflareinsights.com', 'Cloudflare Insights', 'Ads & Tracking', 'Cloudflare'),
    ('fastly.net', 'Fastly', 'Cloud', 'Fastly'),
    ('akamaihd.net', 'Akamai', 'Cloud', 'Akamai'),
    ('akamaized.net', 'Akamai', 'Cloud', 'Akamai'),
    ('digitalocean.com', 'DigitalOcean', 'Cloud', 'DigitalOcean'),
    ('linode.com', 'Akamai Cloud (Linode)', 'Cloud', 'Akamai'),
    ('vultr.com', 'Vultr', 'Cloud', 'Vultr'),
    ('heroku.com', 'Heroku', 'Cloud', 'Salesforce'),
    ('oracle.com', 'Oracle Cloud', 'Cloud', 'Oracle'),
    ('ibm.com', 'IBM Cloud', 'Cloud', 'IBM'),
    ('googlecloud.com', 'Google Cloud', 'Cloud', 'Google LLC'),
    ('gstatic.com', 'Google Static', 'Cloud', 'Google LLC'),
    ('gitlab.com', 'GitLab', 'Development', 'GitLab'),
    ('bitbucket.org', 'Bitbucket', 'Development', 'Atlassian'),
    ('atlassian.com', 'Atlassian', 'Development', 'Atlassian'),
    ('atlassian.net', 'Atlassian Cloud', 'Development', 'Atlassian'),
    ('npmjs.com', 'npm', 'Development', 'npm Inc.'),
    ('npmjs.org', 'npm', 'Development', 'npm Inc.'),
    ('pypi.org', 'PyPI', 'Development', 'Python Software Foundation'),
    ('python.org', 'Python', 'Development', 'PSF'),
    ('docker.com', 'Docker', 'Development', 'Docker Inc.'),
    ('docker.io', 'Docker Hub', 'Development', 'Docker Inc.'),
    ('sourceforge.net', 'SourceForge', 'Development', 'Slashdot Media'),
    ('unity.com', 'Unity', 'Development', 'Unity Technologies'),
    ('wordpress.com', 'WordPress', 'Development', 'Automattic'),
    ('wordpress.org', 'WordPress', 'Development', 'WordPress Foundation'),
    ('wix.com', 'Wix', 'Development', 'Wix.com'),

    # --- Communication ---------------------------------------------------
    ('zoom.us', 'Zoom', 'Communication', 'Zoom'),
    ('zoom.com', 'Zoom', 'Communication', 'Zoom'),
    ('webex.com', 'Webex', 'Communication', 'Cisco'),
    ('gotomeeting.com', 'GoToMeeting', 'Communication', 'GoTo'),
    ('slack.com', 'Slack', 'Communication', 'Salesforce'),
    ('slack-edge.com', 'Slack', 'Communication', 'Salesforce'),
    ('notion.so', 'Notion', 'Work', 'Notion Labs'),
    ('asana.com', 'Asana', 'Work', 'Asana'),
    ('trello.com', 'Trello', 'Work', 'Atlassian'),
    ('monday.com', 'Monday.com', 'Work', 'Monday.com'),
    ('salesforce.com', 'Salesforce', 'Work', 'Salesforce'),
    ('zendesk.com', 'Zendesk', 'Work', 'Zendesk'),
    ('canva.com', 'Canva', 'Work', 'Canva'),
    ('figma.com', 'Figma', 'Work', 'Figma Inc.'),

    # --- Tracking / ads / analytics --------------------------------------
    ('facebook.net', 'Facebook Tracking', 'Ads & Tracking', 'Meta Platforms'),
    ('scorecardresearch.com', 'Comscore', 'Ads & Tracking', 'Comscore'),
    ('quantserve.com', 'Quantcast', 'Ads & Tracking', 'Quantcast'),
    ('adnxs.com', 'AppNexus/Xandr', 'Ads & Tracking', 'Xandr'),
    ('criteo.com', 'Criteo', 'Ads & Tracking', 'Criteo'),
    ('taboola.com', 'Taboola', 'Ads & Tracking', 'Taboola'),
    ('outbrain.com', 'Outbrain', 'Ads & Tracking', 'Outbrain'),
    ('hotjar.com', 'Hotjar', 'Ads & Tracking', 'Hotjar'),
    ('mixpanel.com', 'Mixpanel', 'Ads & Tracking', 'Mixpanel'),
    ('amplitude.com', 'Amplitude', 'Ads & Tracking', 'Amplitude'),
    ('sentry.io', 'Sentry', 'Development', 'Functional Software'),
    ('newrelic.com', 'New Relic', 'Development', 'New Relic'),
    ('branch.io', 'Branch', 'Ads & Tracking', 'Branch Metrics'),
    ('adjust.com', 'Adjust', 'Ads & Tracking', 'Adjust'),
    ('appsflyer.com', 'AppsFlyer', 'Ads & Tracking', 'AppsFlyer'),
    ('firebase.com', 'Firebase', 'Cloud', 'Google LLC'),
    ('firebaseio.com', 'Firebase', 'Cloud', 'Google LLC'),
    ('crashlytics.com', 'Crashlytics', 'Development', 'Google LLC'),

    # --- IoT / smart home -------------------------------------------------
    ('sonos.com', 'Sonos', 'IoT', 'Sonos'),
    ('ring.com', 'Ring', 'IoT', 'Amazon'),
    ('nest.com', 'Nest', 'IoT', 'Google LLC'),
    ('tplink.com', 'TP-Link', 'IoT', 'TP-Link'),
    ('tplinkcloud.com', 'TP-Link Kasa', 'IoT', 'TP-Link'),
    ('tuya.com', 'Tuya Smart', 'IoT', 'Tuya'),
    ('smartthings.com', 'SmartThings', 'IoT', 'Samsung'),
    ('philips-hue.com', 'Philips Hue', 'IoT', 'Signify'),
    ('ring.com', 'Ring', 'IoT', 'Amazon'),
    ('wyze.com', 'Wyze', 'IoT', 'Wyze'),
    ('xiaomi.com', 'Xiaomi', 'IoT', 'Xiaomi'),
    ('mi.com', 'Xiaomi Mi', 'IoT', 'Xiaomi'),
    ('home-assistant.io', 'Home Assistant', 'IoT', 'Nabu Casa'),
    ('raspberrypi.org', 'Raspberry Pi', 'IoT', 'Raspberry Pi Foundation'),

    # --- Finance ----------------------------------------------------------
    ('paypal.com', 'PayPal', 'Finance', 'PayPal'),
    ('stripe.com', 'Stripe', 'Finance', 'Stripe'),
    ('visa.com', 'Visa', 'Finance', 'Visa'),
    ('mastercard.com', 'Mastercard', 'Finance', 'Mastercard'),
    ('barclays.co.uk', 'Barclays', 'Finance', 'Barclays'),
    ('lloydsbank.com', 'Lloyds Bank', 'Finance', 'Lloyds'),
    ('hsbc.co.uk', 'HSBC', 'Finance', 'HSBC'),
    ('monzo.com', 'Monzo', 'Finance', 'Monzo'),
    ('revolut.com', 'Revolut', 'Finance', 'Revolut'),
    ('coinbase.com', 'Coinbase', 'Finance', 'Coinbase'),
    ('binance.com', 'Binance', 'Finance', 'Binance'),
    ('kraken.com', 'Kraken', 'Finance', 'Payward'),
    ('tradingview.com', 'TradingView', 'Finance', 'TradingView'),

    # --- Gambling / adult / dating (filtering categories) -----------------
    ('bet365.com', 'Bet365', 'Gambling', 'Bet365'),
    ('williamhill.com', 'William Hill', 'Gambling', 'Evoke'),
    ('paddypower.com', 'Paddy Power', 'Gambling', 'Flutter'),
    ('betfair.com', 'Betfair', 'Gambling', 'Flutter'),
    ('skybet.com', 'Sky Bet', 'Gambling', 'Flutter'),
    ('pokerstars.com', 'PokerStars', 'Gambling', 'Flutter'),
    ('draftkings.com', 'DraftKings', 'Gambling', 'DraftKings'),
    ('fanduel.com', 'FanDuel', 'Gambling', 'Flutter'),
    ('1xbet.com', '1xBet', 'Gambling', '1xBet'),
    ('pornhub.com', 'Pornhub', 'Adult', 'Aylo'),
    ('xvideos.com', 'XVideos', 'Adult', 'XVideos'),
    ('xhamster.com', 'xHamster', 'Adult', 'Hammy Media'),
    ('xnxx.com', 'XNXX', 'Adult', 'XNXX'),
    ('redtube.com', 'RedTube', 'Adult', 'Aylo'),
    ('onlyfans.com', 'OnlyFans', 'Adult', 'Fenix International'),
    ('chaturbate.com', 'Chaturbate', 'Adult', 'Chaturbate'),
    ('brazzers.com', 'Brazzers', 'Adult', 'Aylo'),
    ('stripchat.com', 'Stripchat', 'Adult', 'Stripchat'),
    ('livejasmin.com', 'LiveJasmin', 'Adult', 'Docler'),
    ('tinder.com', 'Tinder', 'Dating', 'Match Group'),
    ('bumble.com', 'Bumble', 'Dating', 'Bumble Inc.'),
    ('hinge.co', 'Hinge', 'Dating', 'Match Group'),
    ('match.com', 'Match.com', 'Dating', 'Match Group'),
    ('okcupid.com', 'OkCupid', 'Dating', 'Match Group'),
    ('grindr.com', 'Grindr', 'Dating', 'Grindr LLC'),

    # --- VPN / proxy / anonymity (detection reference) -------------------
    ('nordvpn.com', 'NordVPN', 'VPN & Proxy', 'Nord Security'),
    ('expressvpn.com', 'ExpressVPN', 'VPN & Proxy', 'Kape Technologies'),
    ('protonvpn.com', 'Proton VPN', 'VPN & Proxy', 'Proton AG'),
    ('mullvad.net', 'Mullvad VPN', 'VPN & Proxy', 'Mullvad VPN AB'),
    ('surfshark.com', 'Surfshark', 'VPN & Proxy', 'Nord Security'),
    ('cyberghostvpn.com', 'CyberGhost', 'VPN & Proxy', 'Kape Technologies'),
    ('privateinternetaccess.com', 'PIA', 'VPN & Proxy', 'Kape Technologies'),
    ('purevpn.com', 'PureVPN', 'VPN & Proxy', 'GZ Systems'),
    ('ipvanish.com', 'IPVanish', 'VPN & Proxy', 'Ziff Davis'),
    ('hotspotshield.com', 'Hotspot Shield', 'VPN & Proxy', 'Aura'),
    ('windscribe.com', 'Windscribe', 'VPN & Proxy', 'Windscribe'),
    ('tunnelbear.com', 'TunnelBear', 'VPN & Proxy', 'McAfee'),
    ('hide.me', 'Hide.me', 'VPN & Proxy', 'Innovative Connecting'),
    ('vyprvpn.com', 'VyprVPN', 'VPN & Proxy', 'Golden Frog'),
    ('atlasshield.com', 'Atlas VPN', 'VPN & Proxy', 'Nord Security'),
    ('perfect-privacy.com', 'Perfect Privacy', 'VPN & Proxy', 'Perfect Privacy'),
    ('airvpn.org', 'AirVPN', 'VPN & Proxy', 'AirVPN'),
    ('ivpn.net', 'IVPN', 'VPN & Proxy', 'IVPN Ltd'),
    ('azirevpn.com', 'AzireVPN', 'VPN & Proxy', 'AzireVPN'),
    ('ovpn.com', 'OVPN', 'VPN & Proxy', 'OVPN'),
    ('privacytools.io', 'Privacy Tools', 'VPN & Proxy', 'PrivacyTools'),
    ('torproject.org', 'Tor', 'VPN & Proxy', 'Tor Project'),
    ('tor.eff.org', 'Tor', 'VPN & Proxy', 'EFF'),
    ('getlantern.org', 'Lantern', 'VPN & Proxy', 'Lantern'),
    ('psiphon.ca', 'Psiphon', 'VPN & Proxy', 'Psiphon Inc.'),
    ('shadowsocks.org', 'Shadowsocks', 'VPN & Proxy', 'Shadowsocks'),
    ('v2ray.com', 'V2Ray', 'VPN & Proxy', 'V2Ray'),
    ('xray.com', 'Xray', 'VPN & Proxy', 'Xray'),
    ('sing-box.app', 'sing-box', 'VPN & Proxy', 'SagerNet'),
    ('warp.plus', 'Cloudflare WARP', 'VPN & Proxy', 'Cloudflare'),
    ('1.1.1.1', 'Cloudflare WARP', 'VPN & Proxy', 'Cloudflare'),
    ('tailscale.com', 'Tailscale', 'VPN & Proxy', 'Tailscale Inc.'),
    ('zerotier.com', 'ZeroTier', 'VPN & Proxy', 'ZeroTier Inc.'),
    ('hamachi.cc', 'LogMeIn Hamachi', 'VPN & Proxy', 'GoTo'),
    ('openvpn.net', 'OpenVPN', 'VPN & Proxy', 'OpenVPN Inc.'),
    ('wireguard.com', 'WireGuard', 'VPN & Proxy', 'WireGuard'),
    ('softether.org', 'SoftEther', 'VPN & Proxy', 'SoftEther Project'),
    ('hidemyass.com', 'HideMyAss', 'VPN & Proxy', 'Privax'),
    ('hola.org', 'Hola VPN', 'VPN & Proxy', 'Hola Networks'),
    ('betternet.co', 'Betternet', 'VPN & Proxy', 'Aura'),
    ('speedify.com', 'Speedify', 'VPN & Proxy', 'Connectify'),
    ('adguard-vpn.com', 'AdGuard VPN', 'VPN & Proxy', 'AdGuard'),
    ('keepsolid.com', 'KeepSolid VPN', 'VPN & Proxy', 'KeepSolid'),
    ('astrill.com', 'Astrill', 'VPN & Proxy', 'Astrill'),
    ('ivacy.com', 'Ivacy VPN', 'VPN & Proxy', 'PMG'),
    ('fastestvpn.com', 'FastestVPN', 'VPN & Proxy', 'FastestVPN'),
    ('ivacy.net', 'Ivacy', 'VPN & Proxy', 'PMG'),
    ('proxyium.com', 'Web Proxy', 'VPN & Proxy', 'Proxyium'),
    ('proxysite.com', 'Web Proxy', 'VPN & Proxy', 'ProxySite'),
    ('hidemy.name', 'Web Proxy', 'VPN & Proxy', 'HideMy.name'),
    ('kproxy.com', 'Web Proxy', 'VPN & Proxy', 'KProxy'),
    ('croxyproxy.com', 'Web Proxy', 'VPN & Proxy', 'CroxyProxy'),
    ('blockaway.net', 'Web Proxy', 'VPN & Proxy', 'BlockAway'),

    # --- DNS / DoH / DoT (bypass detection reference) --------------------
    ('cloudflare-dns.com', 'Cloudflare DNS (DoH)', 'DNS', 'Cloudflare'),
    ('mozilla.cloudflare-dns.com', 'Cloudflare DNS (DoH)', 'DNS', 'Cloudflare'),
    ('one.one.one.one', 'Cloudflare DNS', 'DNS', 'Cloudflare'),
    ('dns.google', 'Google DNS (DoH)', 'DNS', 'Google LLC'),
    ('dns.quad9.net', 'Quad9 (DoH)', 'DNS', 'Quad9'),
    ('doh.opendns.com', 'OpenDNS (DoH)', 'DNS', 'Cisco'),
    ('doh.dns.sb', 'DNS.SB (DoH)', 'DNS', 'DNS.SB'),
    ('dns.nextdns.io', 'NextDNS (DoH)', 'DNS', 'NextDNS'),
    ('doh.cleanbrowsing.org', 'CleanBrowsing (DoH)', 'DNS', 'CleanBrowsing'),
    ('doh.adguard.com', 'AdGuard DNS (DoH)', 'DNS', 'AdGuard'),
    ('adguard-dns.io', 'AdGuard DNS', 'DNS', 'AdGuard'),
    ('dns.adguard-dns.com', 'AdGuard DNS', 'DNS', 'AdGuard'),
    ('doh.mullvad.net', 'Mullvad DNS', 'DNS', 'Mullvad VPN AB'),
    ('dot.pub', 'DoT Public', 'DNS', 'Various'),
]

# ---------------------------------------------------------------------------
# VPN / proxy detection reference data
# ---------------------------------------------------------------------------

# Domains that indicate the device is talking to a VPN/proxy provider.
VPN_PROVIDER_DOMAINS = {
    'nordvpn.com': 'NordVPN', 'nordvpn.net': 'NordVPN', 'nordvpn.io': 'NordVPN',
    'expressvpn.com': 'ExpressVPN', 'expressvpn.net': 'ExpressVPN',
    'protonvpn.com': 'Proton VPN', 'protonvpn.net': 'Proton VPN',
    'mullvad.net': 'Mullvad VPN', 'mullvad.com': 'Mullvad VPN',
    'surfshark.com': 'Surfshark', 'surfsharkdns.com': 'Surfshark',
    'cyberghostvpn.com': 'CyberGhost', 'privateinternetaccess.com': 'PIA',
    'purevpn.com': 'PureVPN', 'ipvanish.com': 'IPVanish',
    'hotspotshield.com': 'Hotspot Shield', 'windscribe.com': 'Windscribe',
    'tunnelbear.com': 'TunnelBear', 'hide.me': 'Hide.me',
    'vyprvpn.com': 'VyprVPN', 'astrill.com': 'Astrill',
    'perfect-privacy.com': 'Perfect Privacy', 'airvpn.org': 'AirVPN',
    'ivpn.net': 'IVPN', 'azirevpn.com': 'AzireVPN', 'ovpn.com': 'OVPN',
    'hidemyass.com': 'HideMyAss', 'hola.org': 'Hola VPN',
    'torproject.org': 'Tor', 'psiphon.ca': 'Psiphon',
    'getlantern.org': 'Lantern', 'warp.plus': 'Cloudflare WARP',
    'tailscale.com': 'Tailscale', 'zerotier.com': 'ZeroTier',
    'hamachi.cc': 'LogMeIn Hamachi', 'openvpn.net': 'OpenVPN',
    'wireguard.com': 'WireGuard', 'softether.org': 'SoftEther',
    'adguard-vpn.com': 'AdGuard VPN', 'speedify.com': 'Speedify',
    'betternet.co': 'Betternet', 'keepsolid.com': 'KeepSolid VPN',
    'ivacy.com': 'Ivacy VPN', 'fastestvpn.com': 'FastestVPN',
    'shadowsocks.org': 'Shadowsocks', 'v2ray.com': 'V2Ray',
    'xray.com': 'Xray', 'sing-box.app': 'sing-box',
    'proxysite.com': 'Web Proxy', 'croxyproxy.com': 'Web Proxy',
    'kproxy.com': 'Web Proxy', 'blockaway.net': 'Web Proxy',
    'hide.me': 'Hide.me', 'vpnbook.com': 'VPNBook', 'vpn gate': 'VPN Gate',
    'vpngate.net': 'VPN Gate', 'softether.net': 'SoftEther',
    'outline.com': 'Outline VPN', 'getoutline.org': 'Outline VPN',
}

# Public resolvers whose use from a LAN device means "DNS is bypassing the
# router / Pi-hole", which is the most common way to defeat home filtering.
PUBLIC_DNS_IPS = {
    '8.8.8.8': 'Google DNS', '8.8.4.4': 'Google DNS',
    '1.1.1.1': 'Cloudflare DNS', '1.0.0.1': 'Cloudflare DNS',
    '9.9.9.9': 'Quad9', '149.112.112.112': 'Quad9',
    '208.67.222.222': 'OpenDNS', '208.67.220.220': 'OpenDNS',
    '94.140.14.14': 'AdGuard DNS', '94.140.15.15': 'AdGuard DNS',
    '76.76.2.0': 'Control D', '76.76.10.0': 'Control D',
    '45.90.28.0': 'NextDNS', '45.90.30.0': 'NextDNS',
    '64.6.64.6': 'Verisign', '77.88.8.8': 'Yandex DNS',
    '156.154.70.1': 'Neustar', '84.200.69.80': 'DNS.WATCH',
    '185.228.168.9': 'CleanBrowsing', '185.228.169.9': 'CleanBrowsing',
    '162.159.36.1': 'Cloudflare Family', '162.159.46.1': 'Cloudflare Family',
    '10.202.0.1': 'NextDNS (anycast)',
}

DOH_DOMAINS = {
    'cloudflare-dns.com', 'mozilla.cloudflare-dns.com', 'dns.google',
    'dns.quad9.net', 'doh.opendns.com', 'doh.dns.sb', 'dns.nextdns.io',
    'doh.cleanbrowsing.org', 'doh.adguard.com', 'dns.adguard-dns.com',
    'doh.mullvad.net', 'doh.libredns.gr', 'dns.controld.com',
    'freedns.controld.com', 'doh.dnslify.com', 'dot.pub',
    'security.cloudflare-dns.com', 'family.cloudflare-dns.com',
    'chrome.cloudflare-dns.com', 'dns10.quad9.net', 'unfiltered.quad9.net',
}

# Ports/protocols that indicate an encrypted tunnel.
TUNNEL_PORTS = {
    1194: ('OpenVPN', 18),
    1195: ('OpenVPN (alt)', 16),
    1387: ('OpenVPN (alt)', 14),
    1723: ('PPTP', 22),
    1701: ('L2TP', 20),
    500: ('IPsec/IKE', 24),
    4500: ('IPsec NAT-T', 24),
    51820: ('WireGuard', 26),
    51821: ('WireGuard (alt)', 22),
    5555: ('SoftEther', 18),
    8388: ('Shadowsocks', 20),
    8389: ('Shadowsocks (alt)', 18),
    1080: ('SOCKS proxy', 16),
    1081: ('SOCKS proxy', 16),
    9050: ('Tor SOCKS', 24),
    9150: ('Tor Browser SOCKS', 24),
    9001: ('Tor relay', 22),
    9030: ('Tor directory', 22),
    3128: ('HTTP proxy', 12),
    8080: ('HTTP proxy / alt-http', 8),
    8888: ('HTTP proxy', 12),
    8118: ('Privoxy', 14),
    8889: ('Proxy admin', 10),
    4444: ('Various proxy', 8),
    53: ('DNS', 4),
    853: ('DNS over TLS', 18),
    443: ('HTTPS', 2),
}

# IP protocols that are themselves tunnels.
TUNNEL_IP_PROTOS = {
    4: ('IP-in-IP tunnel', 20),
    41: ('IPv6-in-IPv4 tunnel (6in4)', 20),
    47: ('GRE tunnel', 18),
    50: ('ESP (IPsec)', 24),
    51: ('AH (IPsec)', 22),
    97: ('EtherIP', 18),
    115: ('L2TP', 16),
}

# ASN organisation keywords.  Weighted: strong VPN brands / consumer VPN
# hosts, then datacentre hosting (used by proxies and self-hosted VPNs).
VPN_ASN_STRONG = (
    'nordvpn', 'expressvpn', 'mullvad', 'protonvpn', 'surfshark', 'cyberghost',
    'private internet access', 'purevpn', 'ipvanish', 'hotspot shield',
    'windscribe', 'tunnelbear', 'vyprvpn', 'hide.me', 'hola networks',
    'psiphon', 'tor project', 'lantern', 'cloudflare warp', 'warp.plus',
    'tailscale', 'zerotier', 'hamachi', 'logmein', 'perfect privacy',
    'airvpn', 'ivpn', 'azirevpn', 'ovpn', 'astrill', 'keepsolid', 'ivacy',
    'speedify', 'adguard', 'aurengate', 'torguard', 'vpn unlimited',
    'surfshark', 'pia vpn', 'xvpn', 'ivacy', 'hidemyass', 'privax',
)

VPN_ASN_HOSTING = (
    'digitalocean', 'linode', 'akamai connected cloud', 'vultr',
    'choopa', 'ovh', 'hetzner', 'scaleway', 'contabo', 'leaseweb',
    'serverius', 'serverhosh', 'm247', 'datacamp', 'tzulo', 'psychz',
    'quadranet', 'colocrossing', 'frantech', 'buyvm', 'hostwinds',
    'ionos', 'godaddy', 'equinix', 'zenlayer', 'gcore', 'g-core',
    'alibaba cloud', 'tencent cloud', 'huawei cloud', 'oracle cloud',
    'amazon data services', 'amazon technologies', 'google cloud',
    'microsoft azure', 'cloudflare', 'fastly', 'imperva', 'incapsula',
    'stackpath', 'cdn77', 'bunny cdn', 'fly.io', 'render', 'railway',
    'heroku', 'upcloud', 'packethub', 'hostinger', 'namecheap',
    'servers.com', 'hivelocity', 'phoenixnap', 'internap', 'unitas global',
    'privex', 'flokinet', '1984 hosting', 'orangewebsite', 'njal.la',
    'shinjiru', 'koddos', 'abelohost', 'hostkey', 'ihc', 'itldc',
    'aeza', 'vdsina', 'timeweb', 'reg.ru', 'selectel', 'beget',
    'gigahost', 'nforce', 'worldstream', 'serverion', 'cloudie',
    'krypt', 'multacom', 'colohouse', 'sondercloud', 'cogent',
)

# SNI hostname substrings strongly associated with VPN clients.
VPN_HOST_HINTS = (
    'vpn', 'openvpn', 'wireguard', 'wg-', 'tunnel', 'proxy', 'shadowsocks',
    'xray', 'v2ray', 'trojan', 'clash', 'sing-box', 'outline', 'psiphon',
    'stunnel', 'softether', 'l2tp', 'pptp', 'ipsec', 'ikev2', 'hydroxide',
)

# Datacentre traffic from a device is worth flagging only when other signals
# agree; these weights are consumed by :mod:`src.intel.vpnwatch`.
SCORE_WEIGHTS = {
    'asn_vpn_brand': 55.0,
    'asn_hosting': 26.0,
    'provider_domain': 48.0,
    'host_hint': 22.0,
    'tunnel_port': 40.0,
    'tunnel_protocol': 32.0,
    'dns_bypass': 30.0,
    'doh_domain': 34.0,
    'tor': 60.0,
    'public_dns': 26.0,
    'sustained_tunnel': 24.0,
    'nonstandard_tls': 12.0,
    'private_relay': 40.0,
}
